public enum CommandType {
	
	ADD_SONG, DELETE_SONG, SWAP_SONGS,
	GET_READY, PLAY_SONG, JOIN, CREATE, CONFIRM_REQUEST,
	CLOSE, DISCONNECTED, AUTHENTICATION,
	NEARBY_PARTIES,PAUSE,
	UPDATE_PARTY, LOCATION;
}
